modid = "lapisworks"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_lapisworks/_export/generated"

[template]
icon = "icon.png"
include = [
    "lapisworks",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Lapisworks"
author = "Real-Luxof"
show_landing_text = false

[textures.override]
"lapisworks:amel_constructs/diamond_sword" = { texture = "lapisworks:textures/item/amel_dsword_noanim.png" }
"lapisworks:amel_constructs/iron_sword" = { texture = "lapisworks:textures/item/amel_isword_noanim.png" }
"lapisworks:amel_constructs/gold_sword" = { texture = "lapisworks:textures/item/amel_gsword_noanim.png" }

[extra.hexcasting]
# thank you hierophantics lmao
_pattern_regex = { "!Raw" = '(?P<is_per_world>register|registerPerWorld)\("(?P<name>[^"]+)"?,\s"(?P<signature>[qweasd]+)",\sHexDir\.(?P<startdir>\w+)' }
_per_world_value = "registerPerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.package}/init/Patterns.java"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../src"
package = "{src}/main/java/com/luxof/lapisworks"
